### ISSUE TITLE
Visual Indicator of Mode

### ISSUE THREAD

**Issue by mike-lloyd03** [rcmdnk/KE-complex_modifications#6]
I love what you've done both with this Karabiner script and with AHK which I use on my work computer. I like how on AHK, there is a visual aid for what mode you are in. Is there a way to enable this feature in OSX? A script that will run and display the mode when it is switched? Thanks!

**Comment by rcmdnk** [comment]
Thanks for the idea!
It can send shell command so that there could be several ways.

It seems a pop-up alert can be launched by the command:

> [macos - How do I make a Mac Terminal pop-up/alert? Applescript? - Stack Overflow](https://stackoverflow.com/questions/5588064/how-do-i-make-a-mac-terminal-pop-up-alert-applescript)

but it is too much for each vim-mode change.
It is good if the pop up is automatically removed after a short time. (I think it is possible by using shell command, too.)

Another possibility is a combination with other applications.
I made a menu-bar application with [rumps](https://github.com/jaredks/rumps), which makes it easier to make a menu bar app.

> https://rcmdnk.com/blog/2015/11/17/computer-mac-python/

I'll try these possibilities.

**Comment by mike-lloyd03** [comment]
Thanks! A menu bar indicator would be fine. A small one line pop-up on the bottom of the screen the goes away on it's own after a few seconds would be nice too.

**Comment by rcmdnk** [comment]
Now I got it.

There are two ways:

* Display notification:
    Remove old Vim emulation settings, re-import new Vim emulation, and enable it.
    Now you have new setting: 

        Vim emulation: Enable the display notification when the mode is changed: toggle by Ctrl-Cmd-Shift-v

    Once you push `Ctrl`-`Cmd`-`Shift`-`v`, the display notification tells you the current mode.
    Another `Ctrl`-`Cmd`-`Shift`-`v` disables the notification.

* Menu bar notification:
    Install [VEM](https://github.com/rcmdnk/VEM) and run it.

    VEM works with old version of Vim emulation, too.

I like the menu bar notification :grin:

**Comment by mike-lloyd03** [comment]
Thanks! I'll give this a try tonight!

**Comment by mike-lloyd03** [comment]
Okay I just tried it out and I like it! Gets the job done! Thanks so much!
